### ISSUE TITLE
VM1260 preview_frame.html:1 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().

### ISSUE THREAD

**Issue by mbjames** [eee-c/ice-code-editor#121] opened 2016-11-22 01:36 UTC

**Comment by eee-c** [comment] 2016-11-22 02:31
I'm going to close this ticket, but not because I don't care about it. I'm closing it because:

1. It's not an ICE issue. It's a Sounds.js issue. ICE is just running the code that is using Sounds.js. The problem is either in Sounds.js or the code running it. 
2. There isn't enough information. I need the code that generated this error. Without it, I'm debugging blind and would just be guessing.

So... Please open a ticket on the [Sounds.js tracker](https://github.com/eee-c/Sounds.js/issues/new) including the code that is causing the error. I'll check it out as soon as I can :)

**Closed by eee-c** 2016-11-22 02:31 UTC
